runtime: python314
env: standard
entrypoint: gunicorn -b :$PORT main:app

automatic_scaling:
  max_instances: 2

handlers:
  - url: /(.*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|txt|xml|json|pdf|woff|woff2|html))
    static_files: \1
    upload: .*\.(css|js|png|jpg|jpeg|gif|svg|webp|ico|txt|xml|json|pdf|woff|woff2|html)
    secure: always

  - url: /.*
    script: auto
    secure: always
